# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/vladb/Documents/AN2/SEM2/AC/test_env/test_env.cache/wt [current_project]
set_property parent.project_path C:/Users/vladb/Documents/AN2/SEM2/AC/test_env/test_env.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/vladb/Documents/AN2/SEM2/AC/test_env/test_env.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/vladb/Documents/AN2/SEM2/AC/test_env/test_env.srcs/sources_1/new/EX_entity.vhd
  C:/Users/vladb/Documents/AN2/SEM2/AC/test_env/test_env.srcs/sources_1/new/ID_entity.vhd
  C:/Users/vladb/Documents/AN2/SEM2/AC/test_env/test_env.srcs/sources_1/new/IF_entity.vhd
  C:/Users/vladb/Documents/AN2/SEM2/AC/test_env/test_env.srcs/sources_1/new/MEM_entity.vhd
  C:/Users/vladb/Documents/AN2/SEM2/AC/test_env/test_env.srcs/sources_1/new/RF.vhd
  C:/Users/vladb/Documents/AN2/SEM2/AC/test_env/test_env.srcs/sources_1/new/ROM.vhd
  C:/Users/vladb/Documents/AN2/SEM2/AC/test_env/test_env.srcs/sources_1/new/SSD.vhd
  C:/Users/vladb/Documents/AN2/SEM2/AC/test_env/test_env.srcs/sources_1/new/UC_entity.vhd
  C:/Users/vladb/Documents/AN2/SEM2/AC/test_env/test_env.srcs/sources_1/new/WB_entity.vhd
  C:/Users/vladb/Documents/AN2/SEM2/AC/test_env/test_env.srcs/sources_1/new/mpg.vhd
  C:/Users/vladb/Documents/AN2/SEM2/AC/test_env/test_env.srcs/sources_1/new/test_env.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/vladb/Documents/AN2/SEM2/AC/test_env/test_env.srcs/constrs_1/new/test_env.xdc
set_property used_in_implementation false [get_files C:/Users/vladb/Documents/AN2/SEM2/AC/test_env/test_env.srcs/constrs_1/new/test_env.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top test_env -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef test_env.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file test_env_utilization_synth.rpt -pb test_env_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
